### ISSUE TITLE
API simplification: consume I2C and keep it in the struct

### ISSUE THREAD

**Issue by rursprung** [TomSievers/vl53l1x-rs#4]
thanks for this library! may i propose to change the API to simplify it a lot: you can (and should) consume the i2c being passed in in `new` and then keep it in the struct.
this can be done even if the bus is used by multiple devices, as you can use [shared-bus](https://github.com/Rahix/shared-bus) to use the same bus with multiple devices. this way it's not necessary to pass in the i2c every time an API is called.

other I2C device drivers also follow this pattern, see e.g. the [ssd1306 driver](https://github.com/jamwaffles/ssd1306) or the [mpu6050 driver](https://github.com/juliangaal/mpu6050).

if you're ok with this i can contribute a PR to implement this.

**Comment by stijnb1234** [comment]
Implemented in #7, can be closed.

**Comment by rursprung** [comment]
> Implemented in #7, can be closed.

awesome! any chance to get a new release with this?

**Comment by TomSievers** [comment]
Just released a new version, V2.0.0. Which implements this change.
