### ISSUE TITLE
add example(s)

### ISSUE THREAD

**Issue by rursprung** [TomSievers/vl53l1x-rs#5]
could you please add an example which uses this driver to showcase how it should be used (best practices, etc.)?

it'd be great if a minimal example could be added to the README (as is done for most other crates as well) and a full-fledged example (under examples, [see the docs](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples)).

**Comment by TomSievers** [comment]
Added a minimal example and some more examples in the examples folder. If you want more examples, let me know. 

Closing for now
