### ISSUE TITLE
add license.txt to repository

### ISSUE THREAD

**Issue by rursprung** [TomSievers/vl53l1x-rs#6]
you've specified the MIT license in `Cargo.toml`, however there's no corresponding `LICENSE.txt` in the repository itself, thus GitHub cannot identify the license. it'd be great if you could add the `LICENSE.txt` to also allow GH to identify the license. this makes it easier to spot the license at first glance when looking at the repo (on crates.io it's shown correctly).

see the [GitHub docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) for more information.

**Comment by TomSievers** [comment]
License file has been added
